version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless...
      - yarn add serverless -g
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Depolyment started on `date`
      - echo Deploying with Serverless Framework...
      - sls deploy -v -s prod
  post_build:
    commands:
      - echo Deployment finished on `date`